#
# Voice Signal Preprocess
# Copyright (C) 1991-2017 Nationalchip Co., Ltd
#
# Makefile: source list in tb/common
#
#=================================================================================#



common_objs   += common/vsp_context.o

