#
# Voice Signal Preprocess
# Copyright (C) 1991-2017 Nationalchip Co., Ltd
#
# Makefile: source list in tb/algorithm/
#
#=================================================================================#


# common
algorithm_objs      = algorithm/common/algorithm_common.o

# fft
algorithm_objs     += algorithm/fft/algorithm_fft.o

# logfbank
algorithm_objs     += algorithm/logfbank/algorithm_logfbank.o


