#
# Voice Signal Preprocess
# Copyright (C) 1991-2017 Nationalchip Co., Ltd
#
# Makefile: source list in tb/src
#
#=================================================================================#



src_objs   += src/vsp_main.o
src_objs   += src/vsp_process.o
src_objs   += src/vsp_algorithm_implement.o

